<img src="https://ssvp.cl/wp-content/uploads/2015/06/universidad-tecnica-federico-santa-maria.png" width="480" height="240" align="left"/>

# MAT281 - 2° Semestre 2019
## Aplicaciones de la Matemática en la Ingeniería

## Contenidos

* [Numpy](#numpy)
* [Pandas](#pandas)

## Numpy 

NumPy es el paquete fundamental para la computación científica con Python. Contiene entre otras cosas:

 * un poderoso objeto de matriz N-dimensional
 * funciones sofisticadas (de transmisión)
 * herramientas para integrar código C / C ++ y Fortran
 * Álgebra lineal útil, transformada de Fourier y capacidades de números aleatorios

Además de sus obvios usos científicos, NumPy también se puede utilizar como un eficiente contenedor multidimensional de datos genéricos. Se pueden definir tipos de datos arbitrarios. Esto permite que NumPy se integre sin problemas y rápidamente con una amplia variedad de bases de datos.

NumPy tiene licencia bajo la licencia BSD, lo que permite su reutilización con pocas restricciones.

###  Operaciones básicas de NumPy
Las razones por las que debería usar NumPy en lugar de cualquier otro objeto _iterable en Python son:

NumPy proporciona una estructura de ndarray para almacenar datos numéricos de manera contigua.
También implementa operaciones matemáticas rápidas en ndarrays, que explotan esta contigüidad.
Brevedad de la sintaxis para las operaciones de matriz. Un lenguaje como C o Java requeriría que escribamos un bucle para una operación matricial tan simple como C = A + B.

In [1]:
# importar libreria: numpy
import numpy as np

In [2]:
# Arreglo de ceros: np.zeros(shape)
print("Zeros:")
print( np.zeros((3,3)) )

# Arreglos de uno: np.ones(shape)
print("\nOnes:")
print( np.ones((3,3)) )

# Arreglo vacio: np.empty(shape)
print("\nEmpty:")
print( np.empty((3,3)) )

# Rango de valores: np.range(start, stop, step)
print("\nRange:")
print( np.arange(0., 10., 1.) )

# Grilla de valores: np.linspace(start, end, n_values)
print("\nRegular grid:")
print( np.linspace(0., 1., 9) )

# Sequencia aleatoria: np.random
print("\nRandom sequences:")
print( np.random.uniform(10, size=6) )

# Construccion de arreglos: np.array( python_iterable )
print("\nArray constructor")
print( np.array([2, 3, 5, 10, -1]) )

Zeros:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Ones:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Empty:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Range:
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]

Regular grid:
[0.    0.125 0.25  0.375 0.5   0.625 0.75  0.875 1.   ]

Random sequences:
[5.65753991 4.36888498 1.71450217 8.4956632  7.83558    6.91897665]

Array constructor
[ 2  3  5 10 -1]


### Operaciones matemáticas básicas
La mayoría de las operaciones realizadas en NumPy se manejan por elementos, es decir, calcular C = A + B se traducirá en $ C [i, j] = A [i, j] + B [i, j] $. (La excepción es la transmisión y se explicará pronto).

A continuación hay una lista con las operaciones matemáticas más comunes. Para obtener una lista completa, vea aquí: NumPy funciones matemáticas.

In [3]:
# crear dos arreglos
A = np.random.random((5,5))
B = np.random.random((5,5))

# suma
print("Sum:")
print( A+B )

# resta
print("\nSubtraction")
print( A-B )

# producto
print("\nProduct")
print( A*B )

# producto matricial
print("\nMatricial Product")
print( np.dot(A,B) )

# potencia
print("\n Power")
print( A**2 )

# funciones trigonometricas
print("\n np.exp()")
print( np.exp(A) )
print("\n np.sin()")
print( np.sin(A) )
print("\n np.cos()")
print( np.cos(A))
print("\n np.tan()")
print( np.tan(A) )

Sum:
[[0.72777022 1.31149139 0.43778628 1.74242898 0.37283284]
 [0.2580563  0.42327314 0.36488146 0.59960866 1.18537432]
 [0.3369684  0.10436532 0.70310452 0.94106353 0.73369309]
 [1.43698677 0.75663118 1.76153669 1.54268402 1.1678551 ]
 [0.92128416 1.32553007 0.9864641  1.57146621 0.34209011]]

Subtraction
[[ 0.33498417 -0.53477329 -0.24986744 -0.11083534 -0.25400781]
 [-0.08277524 -0.16952317  0.28000473 -0.16822671  0.48250884]
 [ 0.16531386 -0.03692473  0.52675351 -0.92685611  0.35085778]
 [ 0.29745524 -0.03377814 -0.06557736 -0.32400686  0.19632902]
 [ 0.1354463   0.01037762 -0.27238351 -0.16621868 -0.25138108]]

Product
[[0.10435878 0.3585068  0.03230577 0.75594357 0.01862109]
 [0.01493533 0.03760551 0.01368396 0.08280758 0.29307437]
 [0.02155476 0.00238217 0.05422168 0.00663458 0.10380109]
 [0.49411284 0.14283744 0.77467778 0.56872338 0.33133511]
 [0.2076047  0.43923056 0.22472966 0.61046935 0.0134583 ]]

Matricial Product
[[0.66676296 0.97375311 0.99014057 1.54228378 0.73492574

### Operaciones booleanas
Las comparaciones en NumPy funcionan exactamente de la misma manera que las operaciones matemáticas, es decir, en cuanto a elementos. Veamos algunos ejemplos:

In [4]:
# crear dos arreglos 
A = np.array( [[1, 2, 3], [2, 3, 5], [1, 9, 6]] )
B = np.array( [[1, 2, 3], [3, 5, 5], [0, 8, 5]] )

print("A > B:")
print( A > B )

print("\nA =< B:")
print( A <= B )

print("\n A==B:")
print( A==B )

print("\n A!=B:")
print( A!=B )

# crear dos arreglos booleanos
C = A==B
D = A>=B

print("\n A and B:")
print( C & D)
print( np.logical_and(C,D) )

print("\n A or B:")
print( C | D)
print( np.logical_or(C,D) )

print("\n not A:")
print( ~C )
print( np.logical_not(C))

A > B:
[[False False False]
 [False False False]
 [ True  True  True]]

A =< B:
[[ True  True  True]
 [ True  True  True]
 [False False False]]

 A==B:
[[ True  True  True]
 [False False  True]
 [False False False]]

 A!=B:
[[False False False]
 [ True  True False]
 [ True  True  True]]

 A and B:
[[ True  True  True]
 [False False  True]
 [False False False]]
[[ True  True  True]
 [False False  True]
 [False False False]]

 A or B:
[[ True  True  True]
 [False False  True]
 [ True  True  True]]
[[ True  True  True]
 [False False  True]
 [ True  True  True]]

 not A:
[[False False False]
 [ True  True False]
 [ True  True  True]]
[[False False False]
 [ True  True False]
 [ True  True  True]]


## Pandas

pandas es un paquete de Python que proporciona estructuras de datos rápidas, flexibles y expresivas diseñadas para que trabajar con datos "relacionales" o "etiquetados" sea fácil e intuitivo. Su objetivo es ser el bloque de construcción fundamental de alto nivel para hacer análisis de datos prácticos del mundo real en Python. Además, tiene el objetivo más amplio de convertirse en la herramienta de análisis / manipulación de datos de código abierto más potente y flexible disponible en cualquier idioma. Ya está en camino hacia este objetivo.



### Series y DataFrames

* Las *series* son  arreglos unidimensionales con etiquetas. Se puede pensar como una generalización de los diccionarios de Python. 

* Los *dataframe*  son arreglos bidimensionales y una extensión natural de las series. Se puede pensar como la generalización de un numpy.array.


### Operaciones Básicas con series

In [5]:
# importar libreria: pandas, os
import pandas as pd

In [6]:
# crear serie
my_serie = pd.Series(range(3, 33, 3), index=list('abcdefghij'))

# imprimir serie
print("serie:")
print( my_serie )

# tipo 
print("\ntype:")
print( type(my_serie) )

# valores 
print("\nvalues:")
print(my_serie.values)

# indice
print("\nindex:")
print(my_serie.index)

# acceder al valor de la serie: directo
print("\ndirect:")
print(my_serie['b'])

# acceder al valor de la serie: loc
print("\nloc:")
print(my_serie.loc['b'])


# acceder al valor de la serie: iloc
print("\niloc:")
print(my_serie.iloc[1])

# editar valores
print("\nedit:")

print("\nold 'd':",my_serie.loc['d'] )
my_serie.loc['d'] = 1000
print("new 'd':",my_serie.loc['d'] )

serie:
a     3
b     6
c     9
d    12
e    15
f    18
g    21
h    24
i    27
j    30
dtype: int64

type:
<class 'pandas.core.series.Series'>

values:
[ 3  6  9 12 15 18 21 24 27 30]

index:
Index(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'], dtype='object')

direct:
6

loc:
6

iloc:
6

edit:

old 'd': 12
new 'd': 1000


###  Manejo de Fechas

Pandas también trae módulos para trabajar el formato de fechas.

In [7]:
# crear serie de fechas
date_rng = pd.date_range(start='1/1/2019', end='1/02/2019', freq='H')

# imprimir serie
print("serie:")
print( date_rng )

# tipo 
print("\ntype:")
print( type(date_rng) )

# elementos de datetime a string 
string_date_rng = [str(x) for x in date_rng]

print("\ndatetime to string:")
print( string_date_rng )

# elementos de string a datetime 
timestamp_date_rng = pd.to_datetime(string_date_rng, infer_datetime_format=True)

print("\nstring to datetime:")
print( timestamp_date_rng )

serie:
DatetimeIndex(['2019-01-01 00:00:00', '2019-01-01 01:00:00',
               '2019-01-01 02:00:00', '2019-01-01 03:00:00',
               '2019-01-01 04:00:00', '2019-01-01 05:00:00',
               '2019-01-01 06:00:00', '2019-01-01 07:00:00',
               '2019-01-01 08:00:00', '2019-01-01 09:00:00',
               '2019-01-01 10:00:00', '2019-01-01 11:00:00',
               '2019-01-01 12:00:00', '2019-01-01 13:00:00',
               '2019-01-01 14:00:00', '2019-01-01 15:00:00',
               '2019-01-01 16:00:00', '2019-01-01 17:00:00',
               '2019-01-01 18:00:00', '2019-01-01 19:00:00',
               '2019-01-01 20:00:00', '2019-01-01 21:00:00',
               '2019-01-01 22:00:00', '2019-01-01 23:00:00',
               '2019-01-02 00:00:00'],
              dtype='datetime64[ns]', freq='H')

type:
<class 'pandas.core.indexes.datetimes.DatetimeIndex'>

datetime to string:
['2019-01-01 00:00:00', '2019-01-01 01:00:00', '2019-01-01 02:00:00', '2019-01-01 03:00:00',

### Operaciones matemáticas

Al igual que numpy, las series de pandas pueden realizar operaciones matemáticas similares (mientrás los arreglos a operar sean del tipo numérico). Por otro lado existen otras funciones de utilidad.

In [8]:
# crear serie
s1 = pd.Series([1,2,3,4,5])

# maximo
print("max:")
print( s1.max())

# minimo
print("min:")
print( s1.min())

# meadia
print("mean:")
print( s1.mean())

# mediana
print("median:")
print( s1.median())

max:
5
min:
1
mean:
3.0
median:
3.0


###  Masking

Existen módulos para acceder a valores que queremos que cumplan una determinada regla. Por ejemplo, acceder al valor máximo de una serie. En este caso a esta regla la denominaremos *mask*.

In [9]:
# imprimir serie
print("serie:")
print( s1 )

# valor maximo
print("\nvalor maximo:")
print(s1.max() )

# Mask
print("\nmask: search max value")
print(my_serie == max(my_serie) )


# apply mask
print("\nmask: apply mask")
print(my_serie[my_serie == max(my_serie)] )

serie:
0    1
1    2
2    3
3    4
4    5
dtype: int64

valor maximo:
5

mask: search max value
a    False
b    False
c    False
d     True
e    False
f    False
g    False
h    False
i    False
j    False
dtype: bool

mask: apply mask
d    1000
dtype: int64


### Valores Nulos o datos perdidos

En algunas ocaciones, los arreglos no tienen información en una determinada posición, lo cual puede ser perjudicial si no se tiene control sobre estos valores.

In [10]:
# crear serie
s_null = pd.Series([1,2,np.nan,4,5,6,7,np.nan,9])

# imprimir serie
print("serie:")
print( s_null )

# valores nulos
print("\nis null?:")
print(s_null.isnull() )
print("\n null serie")
print(s_null[s_null.isnull()] )


#  valores nulos ? 
print("\nis not null?:")
print(s_null.notnull() )
print("\nserie with not null values")
print(s_null[s_null.notnull()] )

serie:
0    1.0
1    2.0
2    NaN
3    4.0
4    5.0
5    6.0
6    7.0
7    NaN
8    9.0
dtype: float64

is null?:
0    False
1    False
2     True
3    False
4    False
5    False
6    False
7     True
8    False
dtype: bool

 null serie
2   NaN
7   NaN
dtype: float64

is not null?:
0     True
1     True
2    False
3     True
4     True
5     True
6     True
7    False
8     True
dtype: bool

serie with not null values
0    1.0
1    2.0
3    4.0
4    5.0
5    6.0
6    7.0
8    9.0
dtype: float64


### Trabajando  con DataFrames

Como se mencina anteriormente, los dataframes son arreglos de series, los cuales pueden ser de distintos tipos (numéricos, string, etc.). En esta parte mostraremos un ejemplo aplicado de las distintas funcionalidades de los dataframes.

### Lectura de datos

En general, cuando se trabajan con datos, estos se almacenan en algún lugar y en algún tipo de formato, por ejemplo:
 * .txt
 * .csv
 * .xlsx
 * .db
 * etc.
 
Para cada formato, existe un módulo para realizar la lectura de datos. En este caso, se analiza el conjunto de datos 'player_data.csv', el cual muestra informacion básica de algunos jugadores de la NBA.

In [11]:
import os

In [15]:
### lectura de datos
player_data = pd.read_csv(os.path.join('data', 'player_data.csv'), index_col='name')

### Módulos básicos

Existen módulos para comprender rápidamente la naturaleza del dataframe.

In [14]:
# imprimir las primeras 10 filas
print("first 5 rows:")
print(player_data.head(5))

# imprimir las ultimas 10 filas
print("\nlast 5 rows:")
print(player_data.tail(5))

# tipo
print("\ntype of dataframe:")
print(type(player_data))

# tipo por columns
print("\ntype of columns:")
print(player_data.dtypes)

# dimension
print("\nshape:")
print(player_data.shape)

# columna posicion
print("\ncolumn 'position': ")
print(player_data['position'].head())

first 5 rows:
                     year_start  year_end position height  weight  \
name                                                                
Alaa Abdelnaby             1991      1995      F-C   6-10   240.0   
Zaid Abdul-Aziz            1969      1978      C-F    6-9   235.0   
Kareem Abdul-Jabbar        1970      1989        C    7-2   225.0   
Mahmoud Abdul-Rauf         1991      2001        G    6-1   162.0   
Tariq Abdul-Wahad          1998      2003        F    6-6   223.0   

                           birth_date                                college  
name                                                                          
Alaa Abdelnaby          June 24, 1968                        Duke University  
Zaid Abdul-Aziz         April 7, 1946                  Iowa State University  
Kareem Abdul-Jabbar    April 16, 1947  University of California, Los Angeles  
Mahmoud Abdul-Rauf      March 9, 1969             Louisiana State University  
Tariq Abdul-Wahad    Novembe

### Exploración de datos

Existen módulos de pandas que realizan resumen de la información que dispone el dataframe.

In [15]:
# descripcion 
player_data.describe(include='all')

year_start     year_end position height       weight  \
count   4550.000000  4550.000000     4549   4549  4544.000000   
unique          NaN          NaN        7     28          NaN   
top             NaN          NaN        G    6-7          NaN   
freq            NaN          NaN     1574    473          NaN   
mean    1985.076264  1989.272527      NaN    NaN   208.908011   
std       20.974188    21.874761      NaN    NaN    26.268662   
min     1947.000000  1947.000000      NaN    NaN   114.000000   
25%     1969.000000  1973.000000      NaN    NaN   190.000000   
50%     1986.000000  1992.000000      NaN    NaN   210.000000   
75%     2003.000000  2009.000000      NaN    NaN   225.000000   
max     2018.000000  2018.000000      NaN    NaN   360.000000   

               birth_date                 college  
count                4519                    4248  
unique               4161                     473  
top     November 18, 1969  University of Kentucky  
freq                    3                      99  
mean                  NaN                     NaN  
std                   NaN                     NaN  
min                   NaN                     NaN  
25%                   NaN                     NaN  
50%                   NaN                     NaN  
75%                   NaN                     NaN  
max                   NaN                     NaN

### Operando sobre Dataframes

Cuando se trabaja con un conjunto de datos, se crea una dinámica de preguntas y respuestas, en donde a medida que necesito información, se va accediendo al dataframe. En algunas ocaciones es directo, basta un simple módulo, aunque en otras será necesaria realizar operaciones un poco más complejas. 

Por ejemplo, del conjunto de datos en estudio, se esta interesado en responder las siguientes preguntas:


### Determine si el dataframe tiene valores nulos  

In [21]:
player_data.notnull().all(axis=1).head(10)

name
Alaa Abdelnaby          True
Zaid Abdul-Aziz         True
Kareem Abdul-Jabbar     True
Mahmoud Abdul-Rauf      True
Tariq Abdul-Wahad       True
Shareef Abdur-Rahim     True
Tom Abernethy           True
Forest Able             True
John Abramovic          True
Alex Abrines           False
dtype: bool

### Elimine los valores nulos del dataframe

In [24]:
player_data = player_data[lambda df: df.notnull().all(axis=1)]
player_data.head()

year_start  year_end position height  weight  \
name                                                                
Alaa Abdelnaby             1991      1995      F-C   6-10   240.0   
Zaid Abdul-Aziz            1969      1978      C-F    6-9   235.0   
Kareem Abdul-Jabbar        1970      1989        C    7-2   225.0   
Mahmoud Abdul-Rauf         1991      2001        G    6-1   162.0   
Tariq Abdul-Wahad          1998      2003        F    6-6   223.0   

                           birth_date                                college  \
name                                                                           
Alaa Abdelnaby          June 24, 1968                        Duke University   
Zaid Abdul-Aziz         April 7, 1946                  Iowa State University   
Kareem Abdul-Jabbar    April 16, 1947  University of California, Los Angeles   
Mahmoud Abdul-Rauf      March 9, 1969             Louisiana State University   
Tariq Abdul-Wahad    November 3, 1974              San Jose State University   

                     duration  
name                           
Alaa Abdelnaby              4  
Zaid Abdul-Aziz             9  
Kareem Abdul-Jabbar        19  
Mahmoud Abdul-Rauf         10  
Tariq Abdul-Wahad           5

### Determinar el tiempo de cada jugador en su posición.

In [25]:
# Determinar el tiempo de cada jugador en su posición.
player_data['duration'] = player_data['year_end'] - player_data['year_start']
player_data.head()

year_start  year_end position height  weight  \
name                                                                
Alaa Abdelnaby             1991      1995      F-C   6-10   240.0   
Zaid Abdul-Aziz            1969      1978      C-F    6-9   235.0   
Kareem Abdul-Jabbar        1970      1989        C    7-2   225.0   
Mahmoud Abdul-Rauf         1991      2001        G    6-1   162.0   
Tariq Abdul-Wahad          1998      2003        F    6-6   223.0   

                           birth_date                                college  \
name                                                                           
Alaa Abdelnaby          June 24, 1968                        Duke University   
Zaid Abdul-Aziz         April 7, 1946                  Iowa State University   
Kareem Abdul-Jabbar    April 16, 1947  University of California, Los Angeles   
Mahmoud Abdul-Rauf      March 9, 1969             Louisiana State University   
Tariq Abdul-Wahad    November 3, 1974              San Jose State University   

                     duration  
name                           
Alaa Abdelnaby              4  
Zaid Abdul-Aziz             9  
Kareem Abdul-Jabbar        19  
Mahmoud Abdul-Rauf         10  
Tariq Abdul-Wahad           5

### Castear la fecha de str a objeto datetime

In [26]:
# Castear la fecha de str a objeto datetime
player_data['birth_date_dt'] = pd.to_datetime(player_data['birth_date'], format="%B %d, %Y")
player_data.head()

year_start  year_end position height  weight  \
name                                                                
Alaa Abdelnaby             1991      1995      F-C   6-10   240.0   
Zaid Abdul-Aziz            1969      1978      C-F    6-9   235.0   
Kareem Abdul-Jabbar        1970      1989        C    7-2   225.0   
Mahmoud Abdul-Rauf         1991      2001        G    6-1   162.0   
Tariq Abdul-Wahad          1998      2003        F    6-6   223.0   

                           birth_date                                college  \
name                                                                           
Alaa Abdelnaby          June 24, 1968                        Duke University   
Zaid Abdul-Aziz         April 7, 1946                  Iowa State University   
Kareem Abdul-Jabbar    April 16, 1947  University of California, Los Angeles   
Mahmoud Abdul-Rauf      March 9, 1969             Louisiana State University   
Tariq Abdul-Wahad    November 3, 1974              San Jose State University   

                     duration birth_date_dt  
name                                         
Alaa Abdelnaby              4    1968-06-24  
Zaid Abdul-Aziz             9    1946-04-07  
Kareem Abdul-Jabbar        19    1947-04-16  
Mahmoud Abdul-Rauf         10    1969-03-09  
Tariq Abdul-Wahad           5    1974-11-03

### Determinar todas las posiciones.

In [27]:
# Determinar todas las posiciones.
positions = player_data['position'].unique()
positions

array(['F-C', 'C-F', 'C', 'G', 'F', 'F-G', 'G-F'], dtype=object)

### Iterar sobre cada posición y encontrar el mayor valor.

In [28]:
# Iterar sobre cada posición y encontrar el mayor valor.
nba_position_duration = pd.Series()
for position in positions:
    df_aux = player_data.loc[lambda x: x['position'] == position]
    max_duration = df_aux['duration'].max()
    nba_position_duration.loc[position] = max_duration

### Dermine los jugadores más altos de la NBA

In [29]:
height_split = player_data['height'].str.split('-')
for player, height_list in height_split.items():
    if height_list == height_list:
        # Para manejar el caso en que la altura sea nan.
        height = int(height_list[0]) * 30.48 + int(height_list[1]) * 2.54
        player_data.loc[player, "height_cm"] = height
    else:
        player_data.loc[player, "height_cm"] = np.nan

max_height = player_data['height_cm'].max()
tallest_player = player_data.loc[lambda x: x['height_cm'] == max_height].index.tolist()
print(tallest_player)

['Manute Bol']
